### ISSUE TITLE
Task - create a test to validate the weak eTag creation

### ISSUE THREAD

**Issue by benoitdm-oslandia** [benoitdm-oslandia/pg_featureserv#36]
Idées :

```sql_more=
SELECT pg_xact_commit_timestamp(xmin), * FROM YOUR_TABLE_NAME where ID=VALUE;
```

```go
func getWeakETag (table, id) []byte {
    return cache[table][id] 
}
```
Tests:
* [x] écrire un test GET mock sans condition pour vérifier l'etag
* [x] écrire un test GET DB sans condition pour vérifier l'etag
* [x] écrire un test GET mock avec une condition If-None-Match sur l'etag
* [x] écrire un test GET DB avec une condition If-None-Match sur l'etag
* [x] dans les tests, vérifier que l'etag est bien le même après deux GET
* [x] écrire un test vérifiant les etags WEAK et STRONG pour une même feature/représentation différente
----> test TestWeakEtagFromDifferentRepresentationsDb à activer/décommenter dés qu'un autre format que le JSON sera implémenté (GML, HTML ou autre) -> https://git.oslandia.net/Client-projects/geoplateforme-ign-pg-featureserv/-/issues/70
* [x] faire un jeu de tests à part pour les etags

Cache:
* [x] renommer les fonctions du cache pour qu'elles reflètent le type d'etag weak ou strong qu'elles concernent
* [x] ajouter des paramètres à la fonction AddWeakEtag pour la rendre générique (à préciser)
* [x] intégrer les échanges d'etag via l'API sous forme encodée en Base64
* [x] intégrer la valeur du weak etag dans la structure GeoJSON des features
* [x] rédiger la fonction récupérant le weakETag en base si feature déjà présente
* [x] déplacer le cache des etags pour qu'il soit instancié par le catalogue
* [x] ajouter le last modified dans la réponse aux GET sur une feature -> https://git.oslandia.net/Client-projects/geoplateforme-ign-pg-featureserv/-/issues/71

Headers:
* [x] implémenter le traitement du header If-None-Match sur le GET
* [x] implémenter le traitement du header If-None-Match sur les autres méthodes CRUD (PUT/PATCH/?) -> https://git.oslandia.net/Client-projects/geoplateforme-ign-pg-featureserv/-/issues/72
* [x] implémenter le traitement du header If-Match et mettre à jour la documentation swagger -> https://git.oslandia.net/Client-projects/geoplateforme-ign-pg-featureserv/-/issues/73
* [x] mettre à jour la documentation swagger pour If-None-Match

Divers:
* [x] ajouter une API REST pour décomposer un strong en weak -> https://git.oslandia.net/Client-projects/geoplateforme-ign-pg-featureserv/-/issues/74
* [x] intégrer le couple schema + table pour les requêtes en base -> https://git.oslandia.net/Client-projects/geoplateforme-ign-pg-featureserv/-/issues/75
